set shell := ["bash", "-uc"]

current-directory := justfile_directory()

_default:
    @just --list --unsorted

###############################################################################
## Docker
###############################################################################

# Builds the e2e image test runner for quick cli dev
build-test-runner-dev quick-cli-dev-version:
    docker build -t quick-e2e-test-runner --build-arg INDEX=test --build-arg QUICK_CLI_VERSION={{ quick-cli-dev-version }}  .

# Builds the e2e image test runner for quick cli stable
build-test-runner quick-cli-version:
    docker build -t quick-e2e-test-runner --build-arg --build-arg QUICK_CLI_VERSION={{ quick-cli-version }}  .

###############################################################################
## E2E Tests
###############################################################################

# Runs all the e2e tests
run-all-tests api-key quick-host:
    docker run -v {{ current-directory }}:/tests -e X_API_KEY={{ api-key }} -e HOST={{ quick-host }} quick-e2e-test-runner --rm -it

# Runs the e2e CRUD tests
run-crud-tests api-key quick-host:
    docker run -v {{ current-directory }}/crud:/tests/crud -e X_API_KEY={{ api-key }} -e HOST={{ quick-host }} quick-e2e-test-runner --rm -it

# Runs the e2e multi-stream tests
run-multi-stream-tests api-key quick-host:
    docker run -v {{ current-directory }}/multi-stream:/tests/multi-stream -e X_API_KEY={{ api-key }} -e HOST={{ quick-host }} quick-e2e-test-runner --rm -it

# Runs the e2e range tests
run-range-tests api-key quick-host:
    docker run -v {{ current-directory }}/range:/tests/range -e X_API_KEY={{ api-key }} -e HOST={{ quick-host }} quick-e2e-test-runner --rm -it

# Runs the e2e schema tests
run-schema-tests api-key quick-host:
    docker run -v {{ current-directory }}/schema:/tests/schema -e X_API_KEY={{ api-key }} -e HOST={{ quick-host }} quick-e2e-test-runner --rm -it
