apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: [(${name})]
    app.kubernetes.io/component: streamsApp
  annotations:
    d9p.io/has-service: [(${hasService})]
  name: [(${name})]
spec:
  replicas: [(${replicas})]
  selector:
    matchLabels:
      app.kubernetes.io/name: [(${name})]
      app.kubernetes.io/component: streamsApp
  template:
    metadata:
      labels:
        app.kubernetes.io/name: [(${name})]
        app.kubernetes.io/component: streamsApp
    spec:
      containers:
        - image: [(${image})]
          imagePullPolicy: [(${pullPolicy})]
          name: [(${name})]
          [# th:if= "${port}"]
          ports:
            - containerPort: [(${port})]
              protocol: TCP [/]
          args: [# th:each="arg : ${args}"]
            -  [(${ arg })] [/]
          envFrom:
            - configMapRef:
                name: quick-config
          env: [# th:if= "${port}"]
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: CONTAINER_PORT
              value: [(${port})] [/]
            - name: JAVA_TOOL_OPTIONS
              value: "-XX:MinRAMPercentage=45.0 -XX:MaxRAMPercentage=70.0 -Djdk.tls.client.protocols=TLSv1.2"
          resources:
            limits:
              memory: [(${resourceConfig.memory.limit})]
              cpu: [(${resourceConfig.cpu.limit})]
            requests:
              memory: [(${resourceConfig.memory.request})]
              cpu: [(${resourceConfig.cpu.request})]
      [# th:if="${imagePullSecret}"]
      imagePullSecrets:
        - name: [(${imagePullSecret})] [/]
