apiVersion: v1
kind: Service
metadata:
  labels:
    app: [(${name})]
  name: [(${name})]
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: [(${port})]
  selector:
    app.kubernetes.io/name: [(${name})]
    app.kubernetes.io/component: streamsApp
  type: ClusterIP
