type Query {
  findProduct(productId: Long): Product @topic(name: "schema-product-topic-test", keyArgument: "productId")
  findProducts(productId: [Int]): [Product] @topic(name: "schema-product-topic-test", keyArgument: "productId")
  allProducts: [Product] @topic(name: "schema-product-topic-test")
}

type Product {
  productId: Int!,
  name: String,
  description: String,
  price: Price,
  metadata: Metadata
}

type Price {
  total: Float,
  currency: String
}

type Metadata {
  created_at: Int,
  source: String
}
