{
    userRatings(userId: 123, ratingFrom: 1, ratingTo: 5)  {
        userId
        purchase {
            purchaseId
            productId
            price {
                total
                currency
            }
        }
        rating
    }
}
