type Query {
    userRatings(
        userId: Int
        ratingFrom: Int
        ratingTo: Int
    ): [UserRating] @topic(name: "user-rating-range",
        keyArgument: "userId",
        rangeFrom: "ratingFrom",
        rangeTo: "ratingTo")
}
type UserRating {
    userId: Int!
    purchaseId: String!
    purchase: Purchase @topic(name: "purchase-topic-test", keyField: "purchaseId")
    rating: Int
}

type Purchase {
    purchaseId: String!,
    productId: Int!,
    price: Price,
}

type Price {
  total: Float,
  currency: String
}
