type Query {
    productPriceInTime(
        productId: Int
        timestampFrom: Int
        timestampTo: Int
    ): [Product] @topic(name: "product-price-range-test",
        keyArgument: "productId",
        rangeFrom: "timestampFrom",
        rangeTo: "timestampTo")
}

type Product {
    productId: Int!
    name: String
    description: String
    price: Price
    timestamp: Int
}

type Price {
    total: Float
    currency: String
}
