type Query {
    userRatings(
        userId: Int
        ratingFrom: Int
        ratingTo: Int
    ): [UserRating] @topic(name: "user-rating-range",
        keyArgument: "userId",
        rangeFrom: "ratingFrom",
        rangeTo: "ratingTo")

    getUser(userId: Int): UserRating @topic(name: "user-rating-range", keyArgument: "userId")
}
type UserRating {
    userId: Int!
    purchaseId: String!
    rating: Int
}
