name: "Checkstyle validation"
description: "Performs checkstyle validations and fails the task if there are
any warnings or errors"
runs:
  using: "composite"
  steps:
    - name: Set up JDK build 11
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Cache Gradle
      uses: actions/cache@v2
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: checkstyle main
      shell: bash
      run: ./gradlew checkstyleMain

    - name: checkstyle test
      shell: bash
      run: ./gradlew checkstyleTest
