apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.manager.name }}-admin-binding
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "quick.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: manager-admin
subjects:
  - kind: ServiceAccount
    name: {{ include "quick.manager.service.account.name" . }}
    namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.manager.name }}-service-binding
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "quick.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: service-discoverer
subjects:
  - kind: ServiceAccount
    name: {{ include "quick.manager.service.account.name" . }}
    namespace: {{ .Release.Namespace }}
