kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ include "quick.manager.fullname" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.middlewares: {{ .Release.Namespace }}-service-stripprefix@kubernetescrd
    traefik.ingress.kubernetes.io/router.entrypoints: {{ .Values.ingress.entrypoint }}
    traefik.ingress.kubernetes.io/router.tls: {{  .Values.ingress.ssl | quote }}
spec:
  rules:
    - http:
        paths:
          - path: /manager
            pathType: Prefix
            backend:
              service:
                name: {{ include "quick.manager.fullname" . }}
                port:
                  number: 80
      {{- if .Values.ingress.host }}
      host: "{{ .Values.ingress.host }}"
      {{- end }}
