apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: manager-admin
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "quick.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - ""
      - apps
      - extensions
      - batch
      - networking.k8s.io
      - traefik.containo.us
    resources:
      - deployments
      - services
      - ingresses
      - customresourcedefinitions
      - endpoints
      - jobs
      - ingressroutes
      - middlewares
      - pods
      - configmaps
    verbs:
      - update
      - list
      - create
      - watch
      - delete
      - deletecollection
      - get
      - patch
      - put
      - post
