apiVersion: v1
kind: Service
metadata:
  name: {{ include "quick.manager.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "quick.manager.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
  {{- include "quick.manager.selectorLabels" . | nindent 4 }}
