apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: service-stripprefix
  namespace: {{ .Release.Namespace }}

spec:
  stripPrefix:
    prefixes:
      - /manager
      - /ingest
