name: "Validate Gradle Wrapper"
on:
  pull_request:
    paths:
      - 'gradle/wrapper/**'
  push:
    branches: [ master ]
    paths:
      - 'gradle/wrapper/**'

jobs:
  validation:
    name: "Gradle wrapper validation"
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
