name: Workflow for building and publishing Helm charts on GitHub pages

on:
  workflow_call:
    inputs:
      ref:
        description: "The main branch name to checkout the repository."
        required: false
        default: ${{ github.event.repository.default_branch }}
        type: string
      helm-version:
        description: "The helm version."
        required: false
        default: "v3.8.0"
        type: string
      target-branch:
        description: "The branch to push the Helm chart to (default: gh-pages)"
        required: false
        default: gh-pages
        type: string
    secrets:
      github-token:
        description: "The GitHub token for committing the changes."
        required: true
    outputs: { }

jobs:
  helm-release:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.ref}}
          token: ${{ secrets.github-token }}
          path: main

      - name: Setup just
        uses: extractions/setup-just@v1
        env:
          GITHUB_TOKEN: ${{ secrets.github-token }}
        with:
          just-version: 1.5.0

      - name: Setup Helm
        uses: azure/setup-helm@v1
        with:
          version: ${{ inputs.helm-version }}

      - name: Set commit sha
        id: set-commit
        run: | 
          cd ./main
          echo "commitSha=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT

      - name: Package Helm chart
        run: |
          mkdir charts 
          cd main 
          just package-chart ../charts/

      - name: Checkout gh-pages branch
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.target-branch }}
          token: ${{ secrets.github-token }}
          path: gh-pages

      - name: Update Helm index
        run: |
          helm repo index ./charts/ --merge ./gh-pages/index.yaml
          mv ./charts/* ./gh-pages/

      - name: Commit and push new Helm chart
        run: |
          cd ./gh-pages
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          # Add changes
          git add .
          git commit -m "Update Helm chart for ${{ steps.set-commit.outputs.commitSha }}"
          git push
